name: Secrets

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        FLAG: ${{ secrets.FLAG }}
        PASSWORD: ${{ secrets.PASSWORD }}
        IV: ${{ secrets.IV }}
      run: |
        python encrypt.py $FLAG $PASSWORD $IV
